### ISSUE TITLE
Add Project File Fingerprint Endpoint

### ISSUE THREAD

**Issue by justinrusso** [Diluv/Diluv-API#89]
Currently with CurseForge I am utilizing an [API endpoint](https://twitchappapi.docs.apiary.io/#/reference/0/get-addon-by-fingerprint) to obtain information about an addon file by the file itself. As my program at the time may not have any information about what mods currently exist, it would be useful to have a similar way to look up this information.

Specifically, I want to be able to:
1. Determine if this file is hosted by the website or not
2. Get the project id (at the very least) to get the name of the project
3. Get version information of the file, for use in checking if there may be an updated version that currently is not installed.

If necessary, you can find an implementation of how the fingerprint is generated to be sent sent to the API endpoint from the Twitch Export Builder tool: https://github.com/Gaz492/twitch-export-builder/blob/3c2d8f13597998b82c71ce7881eaab991783aab5/utils.go#L193-L200

**Comment by Darkhax** [comment]
Yeah I could definitely see this being useful. We already store a SHA-512 hash of files and it should be trivial to make a reverse lookup endpoint for that which would yield a [ProjectFileRecord](https://github.com/Diluv/Confluencia/blob/82656bd3b7c79e51235dbac2b33d20a6f661fc30/src/main/java/com/diluv/confluencia/database/record/ProjectFileRecord.java). I have no idea what fingerprinting algorithm Curse uses however we only plan to support SHA-512 hashing. Fortunately SHA-512 is standard and libraries/tools exist for every major language and platform.

**Comment by lclc98** [comment]
I have implemented it to show all projects with the file hash under the endpoint /v1/projects/hash/{hash}
I might in the future add it to show the file too, but for now it has the basic implementation. I will keep the issue open.

**Comment by lclc98** [comment]
This should now be properly implemented to show the projects and the files the hash is apart of instead of only the files.
